---
- hosts: localhost
  vars_files:
    - config/github.yml
  roles:
    - role: maid

  environment:
    #make sure linuxbrew will be in path
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"
    RBENV_ROOT: "{{ rbenv_root }}"


  tasks:
    - name: username
      debug: msg={{user}}

    - name: username
      debug: msg={{ rbenv_root }}

    - include: playbooks/bootstrap.yml

    # - name: gh_Debug
    #   debug: msg="On github I am {{ ansible_local.nolith.github.username }}"
