---
- hosts: localhost
  roles:
    - role: maid

  environment:
    #make sure linuxbrew will be in path
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"
    RBENV_ROOT: "{{ rbenv_root }}"


  tasks:
    - name: username
      debug: msg={{user}}

    - name: username
      debug: msg={{ rbenv_root }}

    - include: playbooks/bootstrap.yml
