---
- hosts: localhost
  vars_files:
    - config/github.yml
  roles:
    - role: maid

  environment:
    #make sure linuxbrew will be in path
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"
    RBENV_ROOT: "{{ rbenv_root }}"


  tasks:

#if you need a custom playbook with custom roles
#- include: playbooks/custom.yml
