---
- name: install linuxbrew deps
  apt: name={{item}} state=present update_cache=yes
  sudo: yes
  when: ansible_os_family == 'Debian'
  with_items:
    - zsh
    - build-essential
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev

- name: install linuxbrew
  git: repo=https://github.com/Homebrew/linuxbrew.git dest={{ homebrew_root }} depth=1
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Redhat'
  sudo: true

- name: chown linuxbrew
  file: >
    path={{ homebrew_root }}
    owner={{ user }}
    group={{ user }}
    recurse=yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Redhat'
  sudo: true

- name: rbenv | making RBENV_ROOT
  file: path={{ rbenv_root }} state=directory owner={{ user }}

- name: rbenv | making /opt/rubies
  file: path=/opt/rubies state=directory owner={{ user }}
  sudo: true

- name: rbenv | making RBENV_ROOT/versions
  file: >
    src=/opt/rubies
    dest={{ rbenv_root }}/versions
    state=link

- name: nodenv | making NODENV_ROOT
  file: path={{ nodenv_root }} state=directory owner={{ user }}

- name: nodenv | making /opt/nodes
  file: path=/opt/nodes state=directory owner={{ user }}
  sudo: true

- name: nodenv | making NODENV_ROOT/versions
  file: >
    src=/opt/nodes
    dest={{ nodenv_root }}/versions
    state=link
