#!/usr/bin/env bash
set -e

MAID_ROOT=/opt/maid
echo 'Installing Ansible'

# prefer pip for installing python packages over the older easy_install
#
if [[ ! -x `which pip` ]]; then
    #sudo easy_install pip
    sudo apt-get install -y python-dev python-pip
fi

if [[ -x `which pip` && ! -x `which ansible` ]]; then
    sudo CFLAGS=-Qunused-arguments CPPFLAGS=-Qunused-arguments pip install ansible
fi

echo 'Running Ansible to configure Dev machine'

if [[ -x `which ansible` ]]; then
  ANSIBLE_LOG_PATH=$MAID_ROOT/logs/ansible.log ansible-playbook -i $MAID_ROOT/hosts $MAID_ROOT/site.yml --ask-sudo-pass
fi
